version: '3'
services:
  mongo-container:
    container_name: mongo_catdd
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    build: .
    image: clean-tdd-node-api
    restart: always
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-tdd-node-api/dist
    ports:
      - "4001:4001"
    links:
      - mongo-container
    