version: '3'
services:
  mongo-container:
    container_name: mongo_catdd
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/clean-tdd-node-api
    restart: always
    command: bash -c "npm install && npm run start:watch"
    volumes:
      - ./dist/:/usr/src/clean-tdd-node-api/dist/
      - ./package.json:/usr/src/clean-tdd-node-api/package.json
    ports:
      - "4001:4001"
    links:
      - mongo-container
    